#!/usr/bin/env python

import setuptools

setuptools.setup(
    name='trace_explorer',
    version='1.0',
    description=['Database trace explorer toolset'],
    author='Lennart Espe',
    author_email='lnsp@users.noreply.github.com',
    url='https://espe.tech/trace-explorer',
    install_requires=[
        'attrs==21.4.0',
        'build==0.7.0',
        'click==8.1.3',
        'cloudpickle==2.0.0',
        'cramjam==2.5.0',
        'cycler==0.11.0',
        'dask==2022.4.1',
        'duckdb==0.3.2',
        'fastparquet==0.8.0',
        'flake8==4.0.1',
        'Flask==2.1.2',
        'fonttools==4.29.1',
        'fsspec==2022.2.0',
        'importlib-metadata==4.11.3',
        'iniconfig==1.1.1',
        'itsdangerous==2.1.2',
        'Jinja2==3.1.2',
        'joblib==1.1.0',
        'kiwisolver==1.3.2',
        'locket==0.2.1',
        'MarkupSafe==2.1.1',
        'matplotlib==3.5.1',
        'mccabe==0.6.1',
        'numpy==1.22.2',
        'packaging==21.3',
        'pandas==1.4.1',
        'partd==1.2.0',
        'pdf2image==1.16.0',
        'pep517==0.12.0',
        'Pillow==9.0.1',
        'pluggy==1.0.0',
        'py==1.11.0',
        'pycodestyle==2.8.0',
        'pyflakes==2.4.0',
        'pyparsing==3.0.7',
        'pytest==7.1.0',
        'python-dateutil==2.8.2',
        'pytz==2021.3',
        'PyYAML==6.0',
        'scikit-learn==1.0.2',
        'scipy==1.8.0',
        'six==1.16.0',
        'sklearn==0.0',
        'threadpoolctl==3.1.0',
        'tomli==2.0.1',
        'toolz==0.11.2',
        'Werkzeug==2.1.2',
        'zipp==3.8.0',
    ],
    packages=['trace_explorer'],
    package_data={'trace_explorer': ['web-templates/*.html', 'transformers/*.py']},
    include_package_data=True,
    entry_points={
        'console_scripts': [
            "trace_explorer = trace_explorer.__main__:main"
        ]
    },
)
