#!/usr/bin/env python

import setuptools

setuptools.setup(
        name='trace_explorer',
        version='1.1',
        author='Lennart Espe',
        url='https://github.com/durner/trace-explorer/',
        description=['Database trace explorer toolset'],
        install_requires=[
            'attrs==23.1.0',
            'blinker==1.6.2',
            'build==0.10.0',
            'click==8.1.3',
            'cloudpickle==2.2.1',
            'contourpy==1.0.7',
            'cramjam==2.6.2',
            'cycler==0.11.0',
            'dask==2023.5.1',
            'duckdb==0.8.0',
            'fastparquet==2023.4.0',
            'flake8==6.0.0',
            'Flask==2.3.2',
            'fonttools==4.39.4',
            'fsspec==2023.5.0',
            'importlib-metadata==6.6.0',
            'iniconfig==2.0.0',
            'itsdangerous==2.1.2',
            'Jinja2==3.1.2',
            'joblib==1.2.0',
            'kiwisolver==1.4.4',
            'locket==1.0.0',
            'MarkupSafe==2.1.3',
            'matplotlib==3.7.1',
            'mccabe==0.7.0',
            'numpy==1.24.3',
            'packaging==23.1',
            'pandas==2.0.2',
            'partd==1.4.0',
            'pdf2image==1.16.3',
            'pep517==0.13.0',
            'Pillow==9.5.0',
            'pluggy==1.0.0',
            'py==1.11.0',
            'pycodestyle==2.10.0',
            'pyflakes==3.0.1',
            'pyparsing==3.0.9',
            'pyproject_hooks==1.0.0',
            'pytest==7.3.1',
            'python-dateutil==2.8.2',
            'pytz==2023.3',
            'PyYAML==6.0',
            'scikit-learn==1.2.2',
            'scipy==1.10.1',
            'six==1.16.0',
            'sklearn==0.0.post5',
            'threadpoolctl==3.1.0',
            'tomli==2.0.1',
            'toolz==0.12.0',
            'tzdata==2023.3',
            'Werkzeug==2.3.4',
            'zipp==3.15.0',
    ],
    packages=['trace_explorer'],
    package_data={'trace_explorer': ['web-templates/*.html', 'transformers/*.py']},
    include_package_data=True,
    entry_points={
            'console_scripts': [
                "trace_explorer = trace_explorer.__main__:main"
                ]
            },
)
